# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: true
cache: packages

apt_packages:
  - r-cran-rjava

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
