# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
cache: packages

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo R CMD javareconf ; fi
before_install:
  - sudo $(which R) CMD javareconf

#before_script:
#  - java -version
#  - echo PATH=$PATH
#  - echo JAVA_HOME=$JAVA_HOME
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo R CMD javareconf ; fi
#  - R -e 'Sys.getenv("JAVA_HOME")'
#  - R -e 'library(rJava); .jinit()'

after_success:
  - Rscript -e 'covr::codecov()'
