# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: true
cache: packages

before_install:
  - add-apt-repository ppa:c2d4u.team/c2d4u4.0+
  - apt-get -q update

apt_packages:
  - r-cran-rjava

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
