# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
cache: packages

before_install:
  - sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
  - sudo apt-get -q update
  - sudo apt-get install -y r-cran-rjava

after_script:
  - sudo R CMD javareconf

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
