# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

apt_packages:
 - r-cran-rjava

#warnings_are_errors: true
#sudo: false
#cache: packages

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
